const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  openAudioFile: () => ipcRenderer.invoke('open-audio-file'),
  openAudioFiles: () => ipcRenderer.invoke('open-audio-files'),
  savePreset: (data) => ipcRenderer.invoke('save-preset', data),
  loadPresets: () => ipcRenderer.invoke('load-presets'),
  deletePreset: (id) => ipcRenderer.invoke('delete-preset', id),
  windowAction: (action) => ipcRenderer.invoke('window-action', action),
  assignAudioFile: (data) => ipcRenderer.invoke('assign-audio-file', data),
  saveGiSetlist: (songs) => ipcRenderer.invoke('save-gi-setlist', songs),
  loadGiSetlist: () => ipcRenderer.invoke('load-gi-setlist'),
  syncMongoSetlist: () => ipcRenderer.invoke('sync-mongo-setlist'),
  pushMongoSetlist: (songs) => ipcRenderer.invoke('push-mongo-setlist', songs),
  getAbsolutePath: (relPath) => ipcRenderer.invoke('get-absolute-path', relPath),
  assignDrumSample: (data) => ipcRenderer.invoke('assign-drum-sample', data),
  saveUserDrums: (data) => ipcRenderer.invoke('save-user-drums', data),
  loadUserDrums: () => ipcRenderer.invoke('load-user-drums'),
  loadMidiMap: () => ipcRenderer.invoke('load-midi-map'),
  authSaveSession: (s) => ipcRenderer.invoke('auth-save-session', s),
  authLoadSession: () => ipcRenderer.invoke('auth-load-session'),
  authClearSession: () => ipcRenderer.invoke('auth-clear-session'),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  saveMidiMap: (data) => ipcRenderer.invoke('save-midi-map', data),
  saveMidiMapSync: (data) => { try { return ipcRenderer.sendSync('save-midi-map-sync', data); } catch (e) { return false; } },
  exportMidiMap: (maps) => ipcRenderer.invoke('export-midi-map', maps),
  importMidiMap: () => ipcRenderer.invoke('import-midi-map'),
  fetchChordUrl: (url) => ipcRenderer.invoke('fetch-chord-url', url),
  companionStart: () => ipcRenderer.invoke('companion-start'),
  companionStop: () => ipcRenderer.invoke('companion-stop'),
  companionAllowFirewall: () => ipcRenderer.invoke('companion-allow-firewall'),
  companionOpenHotspot: () => ipcRenderer.invoke('companion-open-hotspot'),
  companionStatus: () => ipcRenderer.invoke('companion-status'),
  companionPublishSong: (song) => ipcRenderer.invoke('companion-publish-song', song),
  companionPublishPlaying: (playing) => ipcRenderer.invoke('companion-publish-playing', playing),
  companionQR: (url) => ipcRenderer.invoke('companion-qr', url),
  companionSetIp: (ip) => ipcRenderer.invoke('companion-set-ip', ip),
  companionGetPrefs: () => ipcRenderer.invoke('companion-get-prefs'),
  companionSetPrefs: (prefs) => ipcRenderer.invoke('companion-set-prefs', prefs),
  stemsSaveCurrent: (state) => ipcRenderer.invoke('stems-save-current', state),
  stemsLoadCurrent: () => ipcRenderer.invoke('stems-load-current'),
  stemsClearCurrent: () => ipcRenderer.invoke('stems-clear-current'),
  stemsSaveFile: (data) => ipcRenderer.invoke('stems-save-file', data),
  stemsRemoveFile: (url) => ipcRenderer.invoke('stems-remove-file', url),
  stemsExportMp3: (data) => ipcRenderer.invoke('stems-export-mp3', data),
  stemsListProjects: () => ipcRenderer.invoke('stems-list-projects'),
  stemsSaveAs: (data) => ipcRenderer.invoke('stems-save-as', data),
  stemsLoadProject: (slug) => ipcRenderer.invoke('stems-load-project', slug),
  stemsDeleteProject: (slug) => ipcRenderer.invoke('stems-delete-project', slug),
  stemsSeparate: (data) => ipcRenderer.invoke('stems-separate', data),
  stemsSeparateCloud: (data) => ipcRenderer.invoke('stems-separate-cloud', data),
  stemsSeparateCancel: () => ipcRenderer.invoke('stems-separate-cancel'),
  onUpdateReady: (cb) => ipcRenderer.on('update-ready', (_e, info) => cb(info)),
  onUpdateProgress: (cb) => ipcRenderer.on('update-progress', (_e, p) => cb(p)),
  onUpdateError: (cb) => ipcRenderer.on('update-error', (_e, e) => cb(e)),
  installUpdate: () => ipcRenderer.invoke('update-install'),
  getAppVersion: () => ipcRenderer.invoke('app-version'),
  checkForUpdates: () => ipcRenderer.invoke('check-for-updates'),
  onStemsSeparateProgress: (cb) => {
    const handler = (_e, payload) => cb(payload);
    ipcRenderer.on('stems-separate-progress', handler);
    return () => ipcRenderer.removeListener('stems-separate-progress', handler);
  }
});
